title: Quantum Mechanics
author: gillec1
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  In this page, I will discuss Quantum Mechanics and all of its important and interesting qualities!
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
